/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRoutesRouteImport } from './routes/saved-routes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DriverLoginRouteImport } from './routes/driver-login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorSignupRouteImport } from './routes/vendor_.signup'
import { Route as VendorLoginRouteImport } from './routes/vendor_.login'
import { Route as VendorTaxisRouteImport } from './routes/vendor.taxis'
import { Route as VendorRoutesRouteImport } from './routes/vendor.routes'
import { Route as VendorEarningsRouteImport } from './routes/vendor.earnings'
import { Route as VendorDriversRouteImport } from './routes/vendor.drivers'
import { Route as VendorBusesRouteImport } from './routes/vendor.buses'
import { Route as VehicleIdRouteImport } from './routes/vehicle.$id'
import { Route as DriverVehiclesRouteImport } from './routes/driver.vehicles'
import { Route as DriverRequestsRouteImport } from './routes/driver.requests'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTaxisRouteImport } from './routes/admin.taxis'
import { Route as AdminSharedTaxiRouteImport } from './routes/admin.shared-taxi'
import { Route as AdminRoutesRouteImport } from './routes/admin.routes'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as ApiVendorCreateDriverRouteImport } from './routes/api/vendor/create-driver'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoutesRoute = SavedRoutesRouteImport.update({
  id: '/saved-routes',
  path: '/saved-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverLoginRoute = DriverLoginRouteImport.update({
  id: '/driver-login',
  path: '/driver-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorSignupRoute = VendorSignupRouteImport.update({
  id: '/vendor_/signup',
  path: '/vendor/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLoginRoute = VendorLoginRouteImport.update({
  id: '/vendor_/login',
  path: '/vendor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorTaxisRoute = VendorTaxisRouteImport.update({
  id: '/taxis',
  path: '/taxis',
  getParentRoute: () => VendorRoute,
} as any)
const VendorRoutesRoute = VendorRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => VendorRoute,
} as any)
const VendorEarningsRoute = VendorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorDriversRoute = VendorDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => VendorRoute,
} as any)
const VendorBusesRoute = VendorBusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => VendorRoute,
} as any)
const VehicleIdRoute = VehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverVehiclesRoute = DriverVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => DriverRoute,
} as any)
const DriverRequestsRoute = DriverRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaxisRoute = AdminTaxisRouteImport.update({
  id: '/taxis',
  path: '/taxis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSharedTaxiRoute = AdminSharedTaxiRouteImport.update({
  id: '/shared-taxi',
  path: '/shared-taxi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoutesRoute = AdminRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const ApiVendorCreateDriverRoute = ApiVendorCreateDriverRouteImport.update({
  id: '/api/vendor/create-driver',
  path: '/api/vendor/create-driver',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRouteWithChildren
  '/driver-login': typeof DriverLoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved-routes': typeof SavedRoutesRoute
  '/search': typeof SearchRoute
  '/vendor': typeof VendorRouteWithChildren
  '/wallet': typeof WalletRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/shared-taxi': typeof AdminSharedTaxiRoute
  '/admin/taxis': typeof AdminTaxisRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/vehicles': typeof DriverVehiclesRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/vendor/buses': typeof VendorBusesRoute
  '/vendor/drivers': typeof VendorDriversRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/routes': typeof VendorRoutesRoute
  '/vendor/taxis': typeof VendorTaxisRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/signup': typeof VendorSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/api/vendor/create-driver': typeof ApiVendorCreateDriverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/driver-login': typeof DriverLoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved-routes': typeof SavedRoutesRoute
  '/search': typeof SearchRoute
  '/wallet': typeof WalletRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/shared-taxi': typeof AdminSharedTaxiRoute
  '/admin/taxis': typeof AdminTaxisRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/vehicles': typeof DriverVehiclesRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/vendor/buses': typeof VendorBusesRoute
  '/vendor/drivers': typeof VendorDriversRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/routes': typeof VendorRoutesRoute
  '/vendor/taxis': typeof VendorTaxisRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/signup': typeof VendorSignupRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/api/vendor/create-driver': typeof ApiVendorCreateDriverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRouteWithChildren
  '/driver-login': typeof DriverLoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved-routes': typeof SavedRoutesRoute
  '/search': typeof SearchRoute
  '/vendor': typeof VendorRouteWithChildren
  '/wallet': typeof WalletRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/shared-taxi': typeof AdminSharedTaxiRoute
  '/admin/taxis': typeof AdminTaxisRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/vehicles': typeof DriverVehiclesRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/vendor/buses': typeof VendorBusesRoute
  '/vendor/drivers': typeof VendorDriversRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/routes': typeof VendorRoutesRoute
  '/vendor/taxis': typeof VendorTaxisRoute
  '/vendor_/login': typeof VendorLoginRoute
  '/vendor_/signup': typeof VendorSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/api/vendor/create-driver': typeof ApiVendorCreateDriverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/dashboard'
    | '/driver'
    | '/driver-login'
    | '/notifications'
    | '/payment-success'
    | '/reset-password'
    | '/saved-routes'
    | '/search'
    | '/vendor'
    | '/wallet'
    | '/admin/bookings'
    | '/admin/coupons'
    | '/admin/drivers'
    | '/admin/notifications'
    | '/admin/refunds'
    | '/admin/revenue'
    | '/admin/routes'
    | '/admin/shared-taxi'
    | '/admin/taxis'
    | '/admin/users'
    | '/admin/vendors'
    | '/driver/earnings'
    | '/driver/requests'
    | '/driver/vehicles'
    | '/vehicle/$id'
    | '/vendor/buses'
    | '/vendor/drivers'
    | '/vendor/earnings'
    | '/vendor/routes'
    | '/vendor/taxis'
    | '/vendor/login'
    | '/vendor/signup'
    | '/admin/'
    | '/driver/'
    | '/vendor/'
    | '/api/vendor/create-driver'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/dashboard'
    | '/driver-login'
    | '/notifications'
    | '/payment-success'
    | '/reset-password'
    | '/saved-routes'
    | '/search'
    | '/wallet'
    | '/admin/bookings'
    | '/admin/coupons'
    | '/admin/drivers'
    | '/admin/notifications'
    | '/admin/refunds'
    | '/admin/revenue'
    | '/admin/routes'
    | '/admin/shared-taxi'
    | '/admin/taxis'
    | '/admin/users'
    | '/admin/vendors'
    | '/driver/earnings'
    | '/driver/requests'
    | '/driver/vehicles'
    | '/vehicle/$id'
    | '/vendor/buses'
    | '/vendor/drivers'
    | '/vendor/earnings'
    | '/vendor/routes'
    | '/vendor/taxis'
    | '/vendor/login'
    | '/vendor/signup'
    | '/admin'
    | '/driver'
    | '/vendor'
    | '/api/vendor/create-driver'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/dashboard'
    | '/driver'
    | '/driver-login'
    | '/notifications'
    | '/payment-success'
    | '/reset-password'
    | '/saved-routes'
    | '/search'
    | '/vendor'
    | '/wallet'
    | '/admin/bookings'
    | '/admin/coupons'
    | '/admin/drivers'
    | '/admin/notifications'
    | '/admin/refunds'
    | '/admin/revenue'
    | '/admin/routes'
    | '/admin/shared-taxi'
    | '/admin/taxis'
    | '/admin/users'
    | '/admin/vendors'
    | '/driver/earnings'
    | '/driver/requests'
    | '/driver/vehicles'
    | '/vehicle/$id'
    | '/vendor/buses'
    | '/vendor/drivers'
    | '/vendor/earnings'
    | '/vendor/routes'
    | '/vendor/taxis'
    | '/vendor_/login'
    | '/vendor_/signup'
    | '/admin/'
    | '/driver/'
    | '/vendor/'
    | '/api/vendor/create-driver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DriverRoute: typeof DriverRouteWithChildren
  DriverLoginRoute: typeof DriverLoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoutesRoute: typeof SavedRoutesRoute
  SearchRoute: typeof SearchRoute
  VendorRoute: typeof VendorRouteWithChildren
  WalletRoute: typeof WalletRoute
  VehicleIdRoute: typeof VehicleIdRoute
  VendorLoginRoute: typeof VendorLoginRoute
  VendorSignupRoute: typeof VendorSignupRoute
  ApiVendorCreateDriverRoute: typeof ApiVendorCreateDriverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-routes': {
      id: '/saved-routes'
      path: '/saved-routes'
      fullPath: '/saved-routes'
      preLoaderRoute: typeof SavedRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-login': {
      id: '/driver-login'
      path: '/driver-login'
      fullPath: '/driver-login'
      preLoaderRoute: typeof DriverLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor_/signup': {
      id: '/vendor_/signup'
      path: '/vendor/signup'
      fullPath: '/vendor/signup'
      preLoaderRoute: typeof VendorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor_/login': {
      id: '/vendor_/login'
      path: '/vendor/login'
      fullPath: '/vendor/login'
      preLoaderRoute: typeof VendorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/taxis': {
      id: '/vendor/taxis'
      path: '/taxis'
      fullPath: '/vendor/taxis'
      preLoaderRoute: typeof VendorTaxisRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/routes': {
      id: '/vendor/routes'
      path: '/routes'
      fullPath: '/vendor/routes'
      preLoaderRoute: typeof VendorRoutesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/earnings': {
      id: '/vendor/earnings'
      path: '/earnings'
      fullPath: '/vendor/earnings'
      preLoaderRoute: typeof VendorEarningsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/drivers': {
      id: '/vendor/drivers'
      path: '/drivers'
      fullPath: '/vendor/drivers'
      preLoaderRoute: typeof VendorDriversRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/buses': {
      id: '/vendor/buses'
      path: '/buses'
      fullPath: '/vendor/buses'
      preLoaderRoute: typeof VendorBusesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vehicle/$id': {
      id: '/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/vehicle/$id'
      preLoaderRoute: typeof VehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/vehicles': {
      id: '/driver/vehicles'
      path: '/vehicles'
      fullPath: '/driver/vehicles'
      preLoaderRoute: typeof DriverVehiclesRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/requests': {
      id: '/driver/requests'
      path: '/requests'
      fullPath: '/driver/requests'
      preLoaderRoute: typeof DriverRequestsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taxis': {
      id: '/admin/taxis'
      path: '/taxis'
      fullPath: '/admin/taxis'
      preLoaderRoute: typeof AdminTaxisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shared-taxi': {
      id: '/admin/shared-taxi'
      path: '/shared-taxi'
      fullPath: '/admin/shared-taxi'
      preLoaderRoute: typeof AdminSharedTaxiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/routes': {
      id: '/admin/routes'
      path: '/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AdminRoutesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/vendor/create-driver': {
      id: '/api/vendor/create-driver'
      path: '/api/vendor/create-driver'
      fullPath: '/api/vendor/create-driver'
      preLoaderRoute: typeof ApiVendorCreateDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminRoutesRoute: typeof AdminRoutesRoute
  AdminSharedTaxiRoute: typeof AdminSharedTaxiRoute
  AdminTaxisRoute: typeof AdminTaxisRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminRoutesRoute: AdminRoutesRoute,
  AdminSharedTaxiRoute: AdminSharedTaxiRoute,
  AdminTaxisRoute: AdminTaxisRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DriverRouteChildren {
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverRequestsRoute: typeof DriverRequestsRoute
  DriverVehiclesRoute: typeof DriverVehiclesRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverEarningsRoute: DriverEarningsRoute,
  DriverRequestsRoute: DriverRequestsRoute,
  DriverVehiclesRoute: DriverVehiclesRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface VendorRouteChildren {
  VendorBusesRoute: typeof VendorBusesRoute
  VendorDriversRoute: typeof VendorDriversRoute
  VendorEarningsRoute: typeof VendorEarningsRoute
  VendorRoutesRoute: typeof VendorRoutesRoute
  VendorTaxisRoute: typeof VendorTaxisRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorBusesRoute: VendorBusesRoute,
  VendorDriversRoute: VendorDriversRoute,
  VendorEarningsRoute: VendorEarningsRoute,
  VendorRoutesRoute: VendorRoutesRoute,
  VendorTaxisRoute: VendorTaxisRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DriverRoute: DriverRouteWithChildren,
  DriverLoginRoute: DriverLoginRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoutesRoute: SavedRoutesRoute,
  SearchRoute: SearchRoute,
  VendorRoute: VendorRouteWithChildren,
  WalletRoute: WalletRoute,
  VehicleIdRoute: VehicleIdRoute,
  VendorLoginRoute: VendorLoginRoute,
  VendorSignupRoute: VendorSignupRoute,
  ApiVendorCreateDriverRoute: ApiVendorCreateDriverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
